// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://LikeButtonDemo',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'show how to build like button'
  ///
  /// [name] : 'fluttercandies://LikeButtonDemo'
  ///
  /// [routeName] : 'like button'
  ///
  /// [description] : 'show how to build like button'
  static const String fluttercandiesLikeButtonDemo =
      'fluttercandies://LikeButtonDemo';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
